In this exerice we will use the method PCA

moeba (https://stats.stackexchange.com/users/28666/amoeba), Making sense of principal component analysis, eigenvectors & eigenvalues, URL (version: 2021-12-03): https://stats.stackexchange.com/q/140579.

EXAMPLE:

We have a collection of wines.
The wines can be described by their color , alchool percentage and many more.

Lets see if we can describe the wine with  less characteristics

We want to find some characteristics which will diffirentiate the wines

Also each characterestics which we will find need to have a large diffrence between the starting characteristics

We are not intersted in getting a subdivision of the standard characterestics but rather create new ones which are correlated with the standard ones

Lets imagine that we have only 2 characterestics.

Each characterestics have different dimensions hence (x,y)

If we wanted to describe them with only 1 dimension (z) what would it be?

https://stats.stackexchange.com/a/140579


Solution:

The new dimension which we will find need to have a large variance

But the difference should be kept minimal

 https://stats.stackexchange.com/a/140579
 
 ( see animation above )
 
The above process is named: Principal Component Analysis
Falls under the category of un-supervised Machine learning - no solutions for the training model
 
Hence: dimensionality reduction


Lets see now an example that we have seen before from the world bank LPI

https://lpi.worldbank.org/

WORLD BANK measures 6 variables:

1) Competence and quality of logistics services

2) Frequency with which shipments reach consignee within scheduled or expected time

3) Ease of arranging competitively priced shipments

4) Quality of trade and transport-related infrastructure

5) Ability to track and trace consignments

6) Efficiency of customs clearance process

Lets see how we will use PCA

In [1]:
# Lets read out data
import pandas as pd

lpi_df = pd.read_csv("International_LPI_2018.csv")
lpi_df

Country   LPI  Customs  Infrastructure  International shipments  \
0         Germany  4.20     4.09            4.37                     3.86   
1          Sweden  4.05     4.05            4.24                     3.92   
2         Belgium  4.04     3.66            3.98                     3.99   
3         Austria  4.03     3.71            4.18                     3.88   
4           Japan  4.03     3.99            4.25                     3.59   
..            ...   ...      ...             ...                      ...   
155  Sierra Leone  2.08     1.82            1.82                     2.18   
156         Niger  2.07     1.77            2.00                     2.00   
157       Burundi  2.06     1.69            1.95                     2.21   
158        Angola  2.05     1.57            1.86                     2.20   
159   Afghanistan  1.95     1.73            1.81                     2.10   

     Logistics quality and competence  Tracking and tracing  Timeliness  
0                                4.31                  4.24        4.39  
1                                3.98                  3.88        4.28  
2                                4.13                  4.05        4.41  
3                                4.08                  4.09        4.25  
4                                4.09                  4.05        4.25  
..                                ...                   ...         ...  
155                              2.00                  2.27        2.34  
156                              2.10                  2.22        2.33  
157                              2.33                  2.01        2.17  
158                              2.00                  2.00        2.59  
159                              1.92                  1.70        2.38  

[160 rows x 8 columns]

In [2]:
# Using the following variables:

lpi_components = [
    'Customs',
    'Infrastructure',
    'International shipments',
    'Logistics quality and competence',
    'Tracking and tracing',
    'Timeliness'
]

lpi_components = lpi_df[lpi_components]
lpi_components

Customs  Infrastructure  International shipments  \
0       4.09            4.37                     3.86   
1       4.05            4.24                     3.92   
2       3.66            3.98                     3.99   
3       3.71            4.18                     3.88   
4       3.99            4.25                     3.59   
..       ...             ...                      ...   
155     1.82            1.82                     2.18   
156     1.77            2.00                     2.00   
157     1.69            1.95                     2.21   
158     1.57            1.86                     2.20   
159     1.73            1.81                     2.10   

     Logistics quality and competence  Tracking and tracing  Timeliness  
0                                4.31                  4.24        4.39  
1                                3.98                  3.88        4.28  
2                                4.13                  4.05        4.41  
3                                4.08                  4.09        4.25  
4                                4.09                  4.05        4.25  
..                                ...                   ...         ...  
155                              2.00                  2.27        2.34  
156                              2.10                  2.22        2.33  
157                              2.33                  2.01        2.17  
158                              2.00                  2.00        2.59  
159                              1.92                  1.70        2.38  

[160 rows x 6 columns]

We have mentioned that PCA uses the variance of the variables .

Hence we have to standardised our data

In [3]:
from sklearn.preprocessing import StandardScaler

standard_scaler = StandardScaler()
lpi_components_standard_scaled = standard_scaler.fit_transform(lpi_components)

In [4]:
from sklearn.decomposition import PCA

pca = PCA(n_components=1)

In [5]:
pca.fit(lpi_components_standard_scaled)

PCA(n_components=1)

In [6]:
# explained_variance_ratio calculated the variance
pca.explained_variance_ratio_

array([0.92257629])

In [7]:
# Using transform we can display the new data onto the dimension ( red dots found in the animation )
transformed = pca.transform(lpi_components_standard_scaled)
transformed[:10]

array([[5.54547364],
       [4.93808946],
       [4.86533482],
       [4.81834623],
       [4.81569261],
       [4.79085083],
       [4.69701109],
       [4.68746366],
       [4.65614658],
       [4.58455542]])

What did PCA found out:

The new dimension is a new linear collection of the already present ones

The components of this dimension are called: components_

Οι συντελεστές των κυρίων συνιστωσών ονομάζονται φορτία (loadings)

In [8]:
pca.components_

array([[0.40728498, 0.41303479, 0.39604297, 0.41660675, 0.41067906,
        0.40552768]])

Lets see it mathematically:

   0,40728498x1+0,41303479x2+0,39604297x3+0,41660675x4+0,41067906x5+0,40552768x6

In [9]:
print(transformed.min(), transformed.max())

-3.816178904589358 5.545473639886474


In [11]:
# Bypass the problem of the range of values above ( -3 to 5) 
#if we use the loadings to calculate the weighted average of the components

import numpy as np

np.average(lpi_components, axis=1, weights=pca.components_[0])[:10]

array([4.2122752 , 4.05869046, 4.03685368, 4.03281921, 4.03928615,
       4.03042283, 4.00731942, 4.00371973, 3.99503935, 3.98022523])

What did we managed to find out

By taking the 6 variables we were able to create a single 1 dimension!

We use this method for example when the dimensions are too many for us to hangle

Or dimensions contain noise

Hence with less dimensions we are able to understand our problems much better

NOTE:

ITS OUR JOB TO FIGURE OUT THE DIMENSIONS AND UNDERSTAND THEM!